# Generated by Django 4.2.7 on 2023-12-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='procedencia',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='platos',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
    ]
